parameters:
#    wanasni_photo.example.class: Wanasni\PhotoBundle\Example

services:
#    wanasni_photo.example:
#        class: %wanasni_photo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
