wanasni_message:
    resource: "@WanasniMessageBundle/Resources/config/routing.yml"
    prefix:   /

wanasni_notification:
    resource: "@WanasniNotificationBundle/Resources/config/routing.yml"
    prefix:   /

wanasni_vehicule:
    resource: "@WanasniVehiculeBundle/Controller"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'default/index.html.twig'


wanasni_user:
    resource: "@WanasniUserBundle/Controller"
    type:     annotation

wanasni_trajet:
    resource: "@WanasniTrajetBundle/Controller"
    type:     annotation


# FosUserBundle Routing EN
fos_user:
    resource: "@WanasniUserBundle/Resources/config/all.xml"

#FosMessageBundle
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messages

